### ISSUE TITLE
Cannot read property 'showNotification' of undefined

### ISSUE THREAD

**Issue by surfjedi** [sagiegurari/angular-web-notification#18]
#### Problem Description

Cool module! thanks! 

I am trying to use this in my project but it appears that this moduleis not getting injected properly?

its built with webpack, ES6 and angular 1.5.8.

Is the angular-web-notification.js file set  up to be exported and used as a module?

#### Code Example

````js

  function vmListCtrl($location, $q, $rootScope, config, dataservice, logger, vmCache, webNotification) {

    /*jshint validthis: true */
    var ctrl = this;

    ctrl.vms = [];

    ctrl.searchFlag = false;
    ctrl.search = {
      status: '!DELETED'
    };

    ctrl.$onInit = function () {
      var promises = [getVMs()];
      return $q.all(promises).then(function () {
        logger.info('Activated vm-list View', config.uiMsgTitle);

        $rootScope.$on('VMsChanged', function () {
          resetAll();
          getVMs();
        });
      });
    };

    function resetAll() {
      ctrl.vms = [];
    }

    function getVMs() {
      return dataservice.getVMs()
        .then(function (data) {
          ctrl.vms = vmCache.get('vms');
          if (ctrl.vms && ctrl.vms.length > 0) {
            ctrl.vms.sort(function (a, b) {
              return a.vm_name > b.vm_name;
            });
          }
        });
    }

    ctrl.searchChanged = function () {
      if (ctrl.searchFlag) {
        ctrl.search.status = '';
      } else {
        ctrl.search.status = '!DELETED';
      }
    };

    ctrl.loadDetails = function (vmName) {
      $location.path('/vm-detail/' + vmName);
    };

    ctrl.vmCreate = function () {
      $location.path('/vm-create');
    };

    ctrl.showAlert = function () {
      webNotification.showNotification(scope.notificationTitle, {
        body: 'scope.notificationText',
        onClick: function onNotificationClicked() {
          console.log('Notification clicked.');
        },
        autoClose: 4000 //auto close the notification after 4 seconds (you can manually close it via hide function)
      }, function onShow(error, hide) {
        if (error) {
          window.alert('Unable to show notification: ' + error.message);
        } else {
          console.log('Notification Shown.');

          setTimeout(function hideNotification() {
            console.log('Hiding notification....');
            hide(); //manually close the notification (you can skip this if you use the autoClose option)
          }, 5000);
        }
      });
    }


  }
export default vmListCtrl;

````

#### Error Stack/Info (if any)

angular.js?7f65:13920 TypeError: [NG-Modular Error] Cannot read property 'showNotification' of undefined
    at vmListCtrl.ctrl.showAlert (eval at 144 (http://localhost:8080/bundle.js:4:17283), <anonymous>:63:20)
    at fn (eval at compile (eval at <anonymous> (http://localhost:8080/vendor.bundle.js:32:27247)), <anonymous>:4:265)
    at expensiveCheckFn (eval at <anonymous> (http://localhost:8080/vendor.bundle.js:32:27247), <anonymous>:15906:18)
    at callback (eval at <anonymous> (http://localhost:8080/vendor.bundle.js:32:27247), <anonymous>:25885:17)
    at Scope.$eval (eval at <anonymous> (http://localhost:8080/vendor.bundle.js:32:27247), <anonymous>:17682:28)
    at Scope.$apply (eval at <anonymous> (http://localhost:8080/vendor.bundle.js:32:27247), <anonymous>:17782:25)
    at HTMLButtonElement.eval (eval at <anonymous> (http://localhost:8080/vendor.bundle.js:32:27247), <anonymous>:25890:23)
    at defaultHandlerWrapper (eval at <anonymous> (http://localhost:8080/vendor.bundle.js:32:27247), <anonymous>:3497:11)
    at HTMLButtonElement.eventHandler (eval at <anonymous> (http://localhost:8080/vendor.bundle.js:32:27247),

**Comment by surfjedi** [comment]
Here is webpack config (where it gets bundled)


````js

var path = require('path'),
    webpack = require('webpack'),
    libPath = path.join(__dirname, 'src/client'),
    wwwPath = path.join(__dirname, 'www'),

// pkg = require('./package.json'),
    CopyWebpackPlugin = require('copy-webpack-plugin'),
    HtmlWebpackPlugin = require('html-webpack-plugin');

/**
 * Env
 * Get npm lifecycle event to identify the environment
 */
var ENV = process.env.npm_lifecycle_event;
var isTest = ENV === 'test' || ENV === 'test-watch';
var isProd = ENV === 'build';



module.exports = function makeWebpackConfig () {
    /**
     * Config
     * Reference: http://webpack.github.io/docs/configuration.html
     * This is the object where all configuration gets set
     */
    var config = {};
    config.context = path.join(__dirname, 'src/client'),

        /**
     * Entry
     * Reference: http://webpack.github.io/docs/configuration.html#entry
     * Should be an empty object if it's generating a test build
     * Karma will set this when it's a test build
     */
    config.entry = isTest ? {} : {
        app: path.join(libPath, 'app/app.module.js'),
        vendor: [
            'jquery',
            'angular',
            'angular-animate',
            'angular-resource',
            'angular-route',
            'angular-sanitize',
            'angular-socket-io',
            'angular-ui-bootstrap',
            'c3',
            'd3',
            'toastr',
            'moment',
            './vendor/ngplus-overlay.js',
            'angular-web-notification'
        ]
    };

    /**
     * Output
     * Reference: http://webpack.github.io/docs/configuration.html#output
     * Should be an empty object if it's generating a test build
     * Karma will handle setting it up for you when it's a test build
     */
    config.output = isTest ? {} : {
        // Absolute output directory
        path: path.join(wwwPath),
        filename: 'bundle.js'
        // filename: 'bundle-[hash:6].js'
    };

    /**
     * Devtool
     * Reference: http://webpack.github.io/docs/configuration.html#devtool
     * Type of sourcemap to use per build type
     */
    if (isTest) {
        config.devtool = 'inline-source-map';
    } else if (isProd) {
        config.devtool = 'source-map';
    } else {
        config.devtool = 'eval-source-map';
    }

    /**
     * Loaders
     * Reference: http://webpack.github.io/docs/configuration.html#module-loaders
     * List: http://webpack.github.io/docs/list-of-loaders.html
     * This handles most of the magic responsible for converting modules
     */

    // Initialize module
    config.module = {
        preLoaders: [],
        loaders: [
            //run all js thru babel
            {
                test: /\.js$/,
                loader: 'babel',
                exclude: /node_modules/,
                query: {
                    presets: ['es2015']
                }
            },
            //load all css into a js bundle which you can require
            {
                test: /\.css$/,
                loader: 'style!css',
                exclude: /node_modules/
            },
            //run all sass thru loader, then css loader, then into js bundle
            {
                test: /\.scss$/,
                loader: 'style!css!sass',
                exclude: /node_modules/
            },
            //load images thru loader and either produce data url or url https://github.com/webpack/url-loader
            {
                test: /\.(eot|woff|woff2|ttf|svg|png|jpg)$/,
                loader: 'url-loader?limit=25000&name=[name].[ext]',
                exclude: /node_modules/
            },
            // https://github.com/webpack/raw-loader
            {
                test: /\.html$/,
                loader: 'raw',
                exclude: /node_modules/
            }
        ]
    };

    // ISPARTA LOADER
    // Reference: https://github.com/ColCh/isparta-instrumenter-loader
    // Instrument JS files with Isparta for subsequent code coverage reporting
    // Skips node_modules and files that end with .test.js
    // if (isTest) {
    //     config.module.preLoaders.push({
    //         test: /\.js$/,
    //         exclude: [
    //             /node_modules/,
    //             /\.spec\.js$/
    //         ],
    //         loader: 'isparta-loader'
    //     })
    // }


    /**
     * Plugins
     * Reference: http://webpack.github.io/docs/configuration.html#plugins
     * List: http://webpack.github.io/docs/list-of-plugins.html
     */
    config.plugins = [

        //try to cut down loading all locale from moment
        new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
        //custom plugin to build module or not
        new webpack.DefinePlugin({
            ON_DEV: process.env.NODE_ENV === 'dev'
        }),
        // OccurenceOrderPlugin: Assign the module and chunk ids by occurrence count. : https://webpack.github.io/docs/list-of-plugins.html#occurenceorderplugin
        new webpack.optimize.OccurenceOrderPlugin(),

        new webpack.optimize.UglifyJsPlugin({
            mangle: false
        }),
        new CopyWebpackPlugin([
            { from: './content', to: './content' },
            { from: 'app/**/*.html' },
            {from: '../../node_modules/bootstrap/dist/css/bootstrap.min.css', to: './vendor/css/bootstrap.min.css'},
            {from: '../../node_modules/angular-ui-bootstrap/dist/ui-bootstrap-csp.css', to: './vendor/css/ui-bootstrap-csp.css'},
            {from: '../../node_modules/font-awesome/fonts', to: './vendor/fonts'},
            {from: '../../node_modules/font-awesome/css/font-awesome.min.css', to: './vendor/css/font-awesome.min.css'},
            {from: '../../node_modules/socket.io-client/socket.io.js', to: './vendor/socket.io.js'}
        ])
    ];

    // Skip rendering index.html in test mode
    if (!isTest) {
        // Reference: https://github.com/ampedandwired/html-webpack-plugin
        // Render index.html
        config.plugins.push(

            //just copied for now since we don't need hasing or anything for now
            // HtmlWebpackPlugin: Simplifies creation of HTML files to serve your webpack bundles : https://www.npmjs.com/package/html-webpack-plugin
            new HtmlWebpackPlugin({
                // filename: 'index.html',
                // template: './app/index.html',
                // pkg: pkg,
                template: path.join(libPath, 'index.html'),
                hash: false,
                title: 'title'

            }),
            new webpack.optimize.CommonsChunkPlugin({
                name: 'vendor',
                filename: 'vendor.bundle.js'
            })
        )
    }

    // Add build specific plugins
    if (isProd) {
        config.plugins.push(
            // Reference: http://webpack.github.io/docs/list-of-plugins.html#noerrorsplugin
            // Only emit files when there are no errors
            new webpack.NoErrorsPlugin(),

            // Reference: http://webpack.github.io/docs/list-of-plugins.html#dedupeplugin
            // Dedupe modules in the output
            new webpack.optimize.DedupePlugin(),

            // Reference: http://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin
            // Minify all javascript, switch loaders to minimizing mode
            new webpack.optimize.UglifyJsPlugin(),

            // Copy assets from the public folder
            // Reference: https://github.com/kevlened/copy-webpack-plugin
            new CopyWebpackPlugin([{
                from: __dirname + '/src/public'
            }])
        )
    }

    /**
     * Dev server configuration
     * Reference: http://webpack.github.io/docs/configuration.html#devserver
     * Reference: http://webpack.github.io/docs/webpack-dev-server.html
     */
    config.devServer = {
        stats: 'minimal',
        historyApiFallback: true,
        inline: true,
        proxy: {
            '/api': {
                target: 'http://localhost:3000',
                secure: false
            }
        }
    };

    return config;
}();

````

**Comment by surfjedi** [comment]
and here is my inital app file

````js

import 'style!css!../../../node_modules/c3/c3.css'

import 'style!css!../../../node_modules/toastr/toastr.css'
// import 'style!css!../../../node_modules/font-awesome/css/font-awesome.min.css'
// import 'style!css!../../../node_modules/bootstrap/dist/css/bootstrap.min.css'
import 'style!css!../../../node_modules/c3/c3.css'



import './blocks/exception/exception.module'
import './blocks/logger/logger.module'
import './blocks/router/router.module'
import './layout/layout.module'
import './dashboard/dashboard.module'
import './widgets/widgets.module'

import  './core/core.module'

window.c3 = require("c3");
window.d3 = require("d3");

  angular.module('app', [
    'ngAnimate', 'ngRoute', 'ngSanitize', 'ngResource',
    'ngplus', 'ui.bootstrap',
    'blocks.exception',
    'blocks.logger',
    'blocks.router',
    /*
     * Order is not important. Angular makes a
     * pass to register all of the modules listed
     * and then when app.dashboard tries to use app.data,
     * its components are available.
     */
    
    /*
     * Everybody has access to these.
     * We could place these under every feature area,
     * but this is easier to maintain.
     */
    'app.core',
    'app.widgets',
    
    /*
     * Feature areas
     */
    'app.dashboard',
    'app.layout',
    'angular-web-notification'

  ]);
  


````

**Comment by sagiegurari** [comment]
never used webpack before, so can't say how it works.
basically the js you load on your browser should load angular first, than web notification and only than your app.js (the part with angular.module('app', [....]) in your last code snippet).
since it is using angular global to define its module and service it doesn't need to 'export' itself to some variable to be used somewhere else.
makes sense?
personally I use bower to fetch the library and than in 1 app browserify and another app I used requirejs. both worked good.

**Comment by sagiegurari** [comment]
was this resolved?

**Comment by sagiegurari** [comment]
I'm closing this due to lack of feedback.
If issue persists reopen the issue.

**Comment by jhourlad** [comment]
Looks like he's only loading the wrapper library (i.e. angular-web-notification). 
You actually have to load the parent js library "simple-web-notification/web-notification.js"

**Comment by sagiegurari** [comment]
I think this issue was opened before i split the library to two

**Comment by aheadwebcloud** [comment]
Hi I am integrating it with the angular 1.6 and build withe webpack , giving below error in console. Any help please.

angular.js:14800 TypeError: Cannot read property 'showNotification' of undefined
    at Object.onCreateService (angular-web-notification.js:102)
    at Object.invoke (angular.js:5106)
    at Object.enforcedReturnValue [as $get] (angular.js:4939)
    at Object.invoke (angular.js:5106)
    at eval (angular.js:4893)
    at getService (angular.js:5047)
    at injectionArgs (angular.js:5072)
    at Object.invoke (angular.js:5098)
    at eval (angular.js:8267)
    at forEach (angular.js:408)

**Comment by sagiegurari** [comment]
this is a closed issue but anyway, make sure the dependency simple-web-notification is installed and loaded
